# Generated by Django 5.1.3 on 2025-02-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoUrbano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('contratistas', models.ManyToManyField(related_name='proyectos', to='Gestion_Proyectos_Urbanos.contratista')),
            ],
        ),
        migrations.CreateModel(
            name='ConstruccionSostenible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Edificio', 'Edificio'), ('Parque', 'Parque'), ('Infraestructura', 'Infraestructura')], max_length=255)),
                ('materiales_sostenibles', models.TextField()),
                ('eficiencia_energetica', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construcciones_sostenibles', to='Gestion_Proyectos_Urbanos.proyectourbano')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaVerde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, help_text='Área en metros cuadrados', max_digits=10)),
                ('ubicacion', models.CharField(max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_verdes', to='Gestion_Proyectos_Urbanos.proyectourbano')),
            ],
        ),
    ]
