# Generated by Django 5.1.3 on 2025-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proyectos_Urbanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='cedula',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
