# Generated by Django 5.1.3 on 2025-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proyectos_Urbanos', '0002_contratista_cedula_alter_contratista_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaverde',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='zonas_verdes/'),
        ),
    ]
