# Generated by Django 5.1.3 on 2025-02-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Proyectos_Urbanos', '0004_remove_proyectourbano_contratistas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectourbano',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_Proyectos_Urbanos.contratista'),
        ),
    ]
